# Étape de build Angular
FROM node:18 as build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build --prod

# Étape de déploiement via NGINX
FROM nginx:alpine

COPY --from=build /app/dist/achatour-frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf